/**
 * bmad_init_project — Initialize a BMad project.
 * Creates _bmad/ directory structure, copies method files reference, creates state.json.
 */

import { Type } from "@sinclair/typebox";
import { mkdir, access, symlink, readFile, writeFile, lstat } from "node:fs/promises";
import { join } from "node:path";
import { createInitialState, writeState, readState, bmadDir } from "../lib/state.ts";
import { generateTeamFile } from "../lib/team-resolver.ts";
import { initBeads, createBead, addDep, isBeadsAvailable } from "../lib/beads.ts";
import type { ToolResult } from "../types.ts";

export const name = "bmad_init_project";
export const description =
  "Initialize a new BMad Method project. Creates _bmad/ directory, symlinks method files, and generates config. Run once per project.";

export const parameters = Type.Object({
  projectPath: Type.String({
    description: "Absolute path to the project root directory",
  }),
  projectName: Type.String({
    description: "Human-readable project name",
  }),
});

export async function execute(
  _id: string,
  params: { projectPath: string; projectName: string },
  context: { bmadMethodPath: string }
): Promise<ToolResult> {
  const { projectPath, projectName } = params;

  // Check if already initialized
  const existing = await readState(projectPath);
  if (existing) {
    return text(
      `Project "${existing.projectName}" is already initialized at ${projectPath}.\n` +
        `Current phase: ${existing.currentPhase}\n` +
        `Active workflow: ${existing.activeWorkflow?.id ?? "none"}\n` +
        `Completed workflows: ${existing.completedWorkflows.map((w) => w.id).join(", ") || "none"}`
    );
  }

  // Verify project directory exists
  try {
    await access(projectPath);
  } catch {
    return text(`Error: Project directory does not exist: ${projectPath}`);
  }

  const bmad = bmadDir(projectPath);
  await mkdir(bmad, { recursive: true });

  // Symlink core/ and bmm/ from the plugin's bundled method files
  // into {project}/_bmad/ so all {project-root}/_bmad/... paths resolve
  const symlinks = ["core", "bmm"];
  for (const dir of symlinks) {
    const target = join(context.bmadMethodPath, dir);
    const link = join(bmad, dir);
    try {
      await lstat(link);
      // Already exists, skip
    } catch {
      await symlink(target, link, "dir");
    }
  }

  // Generate _bmad/bmm/config.yaml with project-specific values
  const configContent = `# BMad Method Configuration — Auto-generated by bmad-method-plugin
# Project: ${projectName}

project_name: "${projectName}"
user_name: "User"
communication_language: "english"
document_output_language: "english"
user_skill_level: "expert"
output_folder: "_bmad-output"
planning_artifacts: "${join(projectPath, "_bmad-output/planning-artifacts")}"
implementation_artifacts: "${join(projectPath, "_bmad-output/implementation-artifacts")}"
product_knowledge: "${join(projectPath, "docs")}"
`;

  // Write config to _bmad/ (not inside the symlinked bmm/ — that's read-only)
  await writeFile(join(bmad, "config.yaml"), configContent, "utf-8");

  // Initialize Beads and seed workflow dependency graph
  let beadsInitialized = false;
  if (await isBeadsAvailable()) {
    try {
      await initBeads(projectPath);

      // Import workflow registry to seed beads
      const { WORKFLOW_REGISTRY } = await import("../lib/workflow-registry.ts");

      // Create project root bead
      await createBead(projectPath, {
        title: `Project: ${projectName}`,
        labels: ["project"],
      });

      // Create workflow beads with phase labels
      const beadIdMap = new Map<string, string>();
      for (const wf of WORKFLOW_REGISTRY) {
        const beadId = await createBead(projectPath, {
          title: wf.id,
          labels: ["workflow", `phase:${wf.phase}`],
          desc: wf.description,
        });
        beadIdMap.set(wf.id, beadId);
      }

      // Wire up dependency graph from requires[]
      for (const wf of WORKFLOW_REGISTRY) {
        const beadId = beadIdMap.get(wf.id);
        if (!beadId) continue;
        for (const reqId of wf.requires ?? []) {
          const reqBeadId = beadIdMap.get(reqId);
          if (reqBeadId) {
            await addDep(projectPath, beadId, reqBeadId);
          }
        }
      }

      beadsInitialized = true;
    } catch (e) {
      // Beads init is non-blocking for now, but warn
      console.error("Beads initialization failed:", e);
    }
  }

  // Create state (uses beads as backend if initialized)
  const state = createInitialState(projectPath, projectName);
  await writeState(projectPath, state);

  // Create output directories
  const outputDir = join(projectPath, "_bmad-output");
  const planningDir = join(outputDir, "planning-artifacts");
  const implDir = join(outputDir, "implementation-artifacts");
  const docsDir = join(projectPath, "docs");
  await mkdir(planningDir, { recursive: true });
  await mkdir(implDir, { recursive: true });
  await mkdir(docsDir, { recursive: true });

  // Generate initial AGENTS.md from filesystem scan (useful for existing projects)
  let teamGenerated = false;
  try {
    const { content } = await generateTeamFile(
      projectPath,
      context.bmadMethodPath,
      projectName
    );
    // Only write if we detected any technologies
    if (content.includes("| ")) {
      await writeFile(join(projectPath, "AGENTS.md"), content, "utf-8");
      teamGenerated = true;
    }
  } catch {
    // Non-critical — AGENTS.md can be generated later
  }

  return text(
    `✅ BMad project "${projectName}" initialized.\n\n` +
      `**Created:**\n` +
      (beadsInitialized ? `- \`.beads/\` — Beads task graph (workflow gating + handoffs)\n` : "") +
      `- \`_bmad/config.yaml\` — project configuration\n` +
      `- \`_bmad/core/\` → symlink to BMad core module\n` +
      `- \`_bmad/bmm/\` → symlink to BMad method module\n` +
      `- \`_bmad-output/planning-artifacts/\` — briefs, PRDs, architecture docs\n` +
      `- \`_bmad-output/implementation-artifacts/\` — sprint status, stories, reviews\n` +
      `- \`docs/\` — project knowledge\n\n` +
      (teamGenerated ? `- \`AGENTS.md\` — recommended subagents and skills for this project\n` : "") +
      `\nAll \`{project-root}/_bmad/...\` paths in BMad step files will resolve correctly.\n\n` +
      `**Next step:** Run \`bmad_list_workflows\` to see available workflows, or start with "Create Product Brief".` +
      (!teamGenerated ? `\n\n💡 Run \`bmad_generate_team\` later to generate AGENTS.md with recommended subagents.` : "")
  );
}

function text(t: string): ToolResult {
  return { content: [{ type: "text", text: t }] };
}
